# Example ALPHANSO Configuration File for a Beam Calculation

# - name: Name of the calculation
# - calc_type: Type of calculation to perform (must be "beam")
# - matdef: Material definition dictionary ({zaid: mass_fraction})
# - beam_energy: Beam energy in MeV
# - an_xs_data_dir: [optional] Path to (a,n) cross section data
# - stopping_power_data_dir: [optional] Path to stopping power data

name: "Example Be-9 Beam Calculation"
calc_type: "beam"
matdef:
  Be-9: 1.0
beam_energy: 5.0
neutron_energy_bins: [12.0, 0.0, 101]
